# Generated by Django 5.0.7 on 2024-09-15 09:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('caption', models.TextField()),
                ('post', models.ImageField(blank=True, null=True, upload_to=api.models.upload_path)),
                ('location', models.CharField(max_length=250)),
                ('tags', models.CharField(max_length=360)),
            ],
        ),
    ]
