# Generated by Django 5.0.7 on 2024-09-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_createpost_caption_alter_createpost_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='created_at',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
