# Generated by Django 5.0.7 on 2024-09-16 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_liked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
