# Generated by Django 5.0.7 on 2024-09-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_createpost_likes_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='tags',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
