# Generated by Django 5.0.7 on 2024-09-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_createpost_likes_alter_createpost_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
