# Generated by Django 5.0.7 on 2024-09-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_createpost_likes_delete_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
