# Generated by Django 5.0.7 on 2024-09-16 16:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_savedpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=1800)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to=api.models.upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='createpost',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
